### ISSUE TITLE
Php example not working...

### ISSUE THREAD

**Issue by technocode** [Schumix/ChatterBotApi#10]
Hi..

i tested on my localhost.. chatterbotapitest.php.. but its not working... no reply form the bot..

**Comment by technocode** [comment]
i modified the function to see the response form fopen...

$context = stream_context_create($contextParams);
$fp = fopen($url, 'rb', false, $context);
$response = stream_get_contents($fp);
echo $response;

i got the following response:
"DENIED +3000_cbfull"

**Comment by megax** [comment]
Hello

I maintain this repo as a fork. I don't do the php part, only c#.
Please report the error to the original owner here: https://github.com/pierredavidbelanger

@megax
