### ISSUE TITLE
I am sad to see that you preferred to fork instead of contributing back to my original project.

### ISSUE THREAD

**Issue by pierredavidbelanger** [Schumix/ChatterBotApi#7]
That being said, should we join our efforts ?

**Comment by megax** [comment]
Currently i only changed so that it would build with my other projects (i want to be able to build the whole thing inside monodevelop or VS). The later fixes that aired not neccessarily were for my own goal. I noticed them that i don't develop in anything but c# but if they want to send patches i will accept it. If i created inconvenience for you i apologize. As i said i only have own fork to have a mirror that builds with my projects. I am open to suggestions.

**Comment by pierredavidbelanger** [comment]
There is no real inconvenience, no need to apologize :)

I am glad that my project is alive and receiving care somewhere else.
But I still would have preferred to see him grow (fork + pull request) rather than forking alone.

I will soon move my original Chatter Bot API project to GitHub (almost all my projects are here anyways).
As soon as I do this, I will get back to you. Maybe, then, we should merge our commits.

In the meantime, if you can reference my original project somewhere it would be greatly appreciated, but of course I will not mandate you to do so.

Thank you!

**Comment by pierredavidbelanger** [comment]
FYI: I referenced your project on my home page https://code.google.com/p/chatter-bot-api/

**Comment by megax** [comment]
I referred you as well: https://github.com/Schumix/ChatterBotApi
I can give you also my repo's admin if you want when you want to join to GitHub if it's simple for you.

**Comment by pierredavidbelanger** [comment]
I finally moved my project to GitHub (https://github.com/pierredavidbelanger/chatter-bot-api).
I will no longer maintain the Google Code page.
You can now either:
- keep you work separated in your repo
- or clone my repo, hand merge your changes/additions and send me pull requests (ideally in concern related subject branches)
  Thank you!

**Comment by megax** [comment]
I'd like to keep things as it is now, I will send you the fixes. Please specify which fixes do you want to be sent to you.

**Comment by pierredavidbelanger** [comment]
No problem :)

I do not know exactly what you changed from my version.
So if you think something would interesting to add to my version, do not hesitate.

Anyways, I will keep the reference to your project on the home page so people know your repo is a fork (even if it is not a GitHub fork).

Thank you!

**Comment by megax** [comment]
I sent the first 5 changes:
- https://github.com/pierredavidbelanger/chatter-bot-api/pull/1
- https://github.com/pierredavidbelanger/chatter-bot-api/pull/2
- https://github.com/pierredavidbelanger/chatter-bot-api/pull/3
- https://github.com/pierredavidbelanger/chatter-bot-api/pull/4
- https://github.com/pierredavidbelanger/chatter-bot-api/pull/5

**Comment by megax** [comment]
Can i do still something for you or is it okay if i close the issue? :)

**Comment by pierredavidbelanger** [comment]
It is nice, and I really appreciate what you have done.
You can indeed close this issue.
Thank you!

**Comment by megax** [comment]
You are welcome :)
