### ISSUE TITLE
Difference between using cleverbot.com and ChatterBotApi

### ISSUE THREAD

**Issue by IDmedia** [Schumix/ChatterBotApi#8]
When running the dotnet demo, it doesn't take long before I'm starting to get 403 Forbidden errors. I guess there's a hard limit on how much I may use the cleverbot api? However, the strange thing is that just the api get's cut off, the website still works.

I intend to make a fork of this and rewrite it so I scrape the result from the website instead of using the api. Or is there a better way of solving this?

Goig to http://www.cleverbot.com/webservicemin gives me: DENIED +3000_cbfull

**Comment by megax** [comment]
I've never encountered such problem and i think api is a better solution, but if you write it as an alternate and send it in, i can add it to code (so the api and the web query would be available to choose too)
